#!/usr/bin/env bash
set -euxo pipefail

# Inspired by: https://www.openshift.com/blog/mitigate-impact-of-docker-hub-pull-request-limits

skopeo login --username "$QUAY_USER" --password-stdin quay.io <<< "$QUAY_PASS"
skopeo sync --src docker --dest docker docker.io/python:3.9-slim-buster quay.io/pycontribs/
